-- Generated by scripts/build-supabase-seed.js — do not edit by hand.
-- Source: seed-data/*.json

-- Idempotent: truncate lets the seed be re-run against a dev database
-- without stacking duplicate rows. RESTART IDENTITY keeps ids stable
-- across reseeds, which matters because the client treats them as
-- meaningful numbers.
truncate public.doctors, public.drugs, public.pharmacies restart identity cascade;

-- doctors: 22 rows
insert into public.doctors (name, specialization, hospital, location, region, phone, email, latitude, longitude, experience_years, rating, availability, available) values
  ('Dr. Sarah Mwangi', 'General Practitioner', 'Kenyatta National Hospital', 'Nairobi, Kenya', 'nairobi', '+254712345678', 'sarah.mwangi@knh.co.ke', -1.301, 36.8073, 8, 4.8, 'Mon-Fri 8am-5pm', true),
  ('Dr. James Kariuki', 'Cardiologist', 'Nairobi Hospital', 'Nairobi, Kenya', 'nairobi', '+254723456789', 'j.kariuki@nairobihospital.co.ke', -1.2921, 36.8219, 14, 4.9, 'Mon-Wed 9am-4pm', true),
  ('Dr. Aisha Patel', 'Pediatrician', 'Aga Khan University Hospital', 'Nairobi, Kenya', 'nairobi', '+254734567890', 'a.patel@agakhan.co.ke', -1.2637, 36.8031, 6, 4.7, 'Mon-Fri 8am-6pm', true),
  ('Dr. Grace Njoroge', 'Gynaecologist', 'MP Shah Hospital', 'Nairobi, Kenya', 'nairobi', '+254756789012', 'grace.n@mpshah.co.ke', -1.2764, 36.8166, 12, 4.9, 'Mon-Fri 8am-5pm', true),
  ('Dr. Peter Kamau', 'Orthopaedic Surgeon', 'Karen Hospital', 'Nairobi, Kenya', 'nairobi', '+254767890123', 'p.kamau@karenhospital.co.ke', -1.3187, 36.7097, 16, 4.7, 'Mon-Thu 8am-4pm', true),
  ('Dr. Mark Odhiambo', 'Dermatologist', 'Gertrude''s Children Hospital', 'Nairobi, Kenya', 'nairobi', '+254745678901', 'mark.o@gertrudeshosp.co.ke', -1.258, 36.8036, 10, 4.6, 'Tue-Sat 9am-5pm', false),
  ('Dr. Lucy Wanjiru', 'General Practitioner', 'Nakuru Level 5 Hospital', 'Nakuru, Kenya', 'nakuru', '+254711111001', 'lucy.w@nakuruhospital.co.ke', -0.2833, 36.0667, 7, 4.6, 'Mon-Fri 8am-5pm', true),
  ('Dr. Robert Mutai', 'Cardiologist', 'Rift Valley Provincial Hospital', 'Nakuru, Kenya', 'nakuru', '+254711111002', 'r.mutai@rvph.co.ke', -0.2956, 36.0731, 11, 4.7, 'Mon-Wed 9am-4pm', true),
  ('Dr. Faith Chebet', 'Pediatrician', 'Nakuru War Memorial Hospital', 'Nakuru, Kenya', 'nakuru', '+254711111003', 'f.chebet@warmed.co.ke', -0.2775, 36.0743, 5, 4.8, 'Mon-Fri 8am-6pm', true),
  ('Dr. Samuel Koech', 'Gynaecologist', 'Milimani Medical Centre', 'Nakuru, Kenya', 'nakuru', '+254711111004', 's.koech@milimani.co.ke', -0.2889, 36.0521, 9, 4.5, 'Tue-Sat 9am-5pm', true),
  ('Dr. Hassan Omar', 'General Practitioner', 'Coast General Teaching Hospital', 'Mombasa, Kenya', 'mombasa', '+254722222001', 'h.omar@coastgeneral.co.ke', -4.0435, 39.6682, 9, 4.7, 'Mon-Fri 8am-5pm', true),
  ('Dr. Fatuma Ali', 'Pediatrician', 'Pandya Memorial Hospital', 'Mombasa, Kenya', 'mombasa', '+254722222002', 'f.ali@pandya.co.ke', -4.0534, 39.6601, 6, 4.6, 'Mon-Sat 8am-6pm', true),
  ('Dr. David Karisa', 'Orthopaedic Surgeon', 'Aga Khan Hospital Mombasa', 'Mombasa, Kenya', 'mombasa', '+254722222003', 'd.karisa@agakhanmsa.co.ke', -4.058, 39.665, 13, 4.9, 'Mon-Fri 9am-4pm', true),
  ('Dr. Amina Shafi', 'Dermatologist', 'Mombasa Hospital', 'Mombasa, Kenya', 'mombasa', '+254722222004', 'a.shafi@mombasahospital.co.ke', -4.062, 39.67, 7, 4.5, 'Tue-Sat 9am-5pm', false),
  ('Dr. Otieno Omondi', 'General Practitioner', 'Jaramogi Oginga Odinga Teaching Hospital', 'Kisumu, Kenya', 'kisumu', '+254733333001', 'o.omondi@jootrh.co.ke', -0.0917, 34.768, 10, 4.7, 'Mon-Fri 8am-5pm', true),
  ('Dr. Anyango Achieng', 'Gynaecologist', 'Kisumu County Referral Hospital', 'Kisumu, Kenya', 'kisumu', '+254733333002', 'a.achieng@kisumucounty.co.ke', -0.1022, 34.7617, 8, 4.8, 'Mon-Fri 8am-6pm', true),
  ('Dr. Collins Ouma', 'Cardiologist', 'Aga Khan Hospital Kisumu', 'Kisumu, Kenya', 'kisumu', '+254733333003', 'c.ouma@agakhankisumu.co.ke', -0.0836, 34.76, 15, 4.9, 'Mon-Thu 9am-4pm', true),
  ('Dr. Kipchoge Rono', 'General Practitioner', 'Moi Teaching & Referral Hospital', 'Eldoret, Kenya', 'eldoret', '+254744444001', 'k.rono@mtrh.co.ke', 0.5143, 35.2698, 9, 4.7, 'Mon-Fri 8am-5pm', true),
  ('Dr. Eunice Sang', 'Pediatrician', 'Eldoret Hospital', 'Eldoret, Kenya', 'eldoret', '+254744444002', 'e.sang@eldorethospital.co.ke', 0.521, 35.275, 6, 4.6, 'Mon-Sat 8am-6pm', true),
  ('Dr. Brian Mutai', 'Orthopaedic Surgeon', 'Moi Teaching & Referral Hospital', 'Eldoret, Kenya', 'eldoret', '+254744444003', 'b.mutai@mtrh.co.ke', 0.5143, 35.2698, 12, 4.8, 'Tue-Sat 9am-5pm', false),
  ('Dr. Anne Waweru', 'General Practitioner', 'Thika Level 5 Hospital', 'Thika, Kenya', 'thika', '+254755555001', 'a.waweru@thikahospital.co.ke', -1.0332, 37.0693, 7, 4.5, 'Mon-Fri 8am-5pm', true),
  ('Dr. Joseph Maina', 'Dermatologist', 'Thika District Hospital', 'Thika, Kenya', 'thika', '+254755555002', 'j.maina@thikadist.co.ke', -1.039, 37.074, 8, 4.6, 'Mon-Fri 9am-5pm', true);

-- drugs: 8 rows
insert into public.drugs (name, generic_name, category, uses, dosage, side_effects, pregnancy_safe, alcohol_safe, lactation_safe, prescription_required) values
  ('Amoxicillin', 'Amoxicillin', 'Antibiotic', 'Treats bacterial infections including pneumonia, ear infections, UTIs, and skin infections.', 'Adults: 250-500mg every 8 hours. Children: 25mg/kg/day in divided doses.', 'Nausea, diarrhea, rash, allergic reactions.', true, false, true, 'Yes'),
  ('Paracetamol', 'Acetaminophen', 'Analgesic / Antipyretic', 'Relieves mild to moderate pain and reduces fever.', 'Adults: 500-1000mg every 4-6 hours. Max 4g/day. Children: 10-15mg/kg every 4-6 hours.', 'Rarely causes side effects at normal doses. Overdose can cause liver damage.', true, false, true, 'No'),
  ('Metformin', 'Metformin Hydrochloride', 'Antidiabetic', 'Controls blood sugar levels in type 2 diabetes.', 'Adults: 500mg twice daily with meals. Max 2000mg/day.', 'Nausea, vomiting, diarrhea, stomach upset.', false, false, false, 'Yes'),
  ('Ibuprofen', 'Ibuprofen', 'NSAID / Anti-inflammatory', 'Reduces pain, fever and inflammation. Used for headaches, arthritis, menstrual cramps.', 'Adults: 200-400mg every 4-6 hours. Max 1200mg/day without prescription.', 'Stomach upset, heartburn, nausea, increased bleeding risk.', false, false, false, 'No'),
  ('Ciprofloxacin', 'Ciprofloxacin', 'Antibiotic', 'Treats urinary tract infections, respiratory infections, typhoid fever.', 'Adults: 250-750mg twice daily for 7-14 days.', 'Nausea, diarrhea, dizziness, tendon damage with prolonged use.', false, false, false, 'Yes'),
  ('Artemether/Lumefantrine', 'Artemether + Lumefantrine', 'Antimalarial', 'First-line treatment for uncomplicated malaria in Kenya.', 'Adults: 4 tablets at 0, 8, 24, 36, 48, 60 hours (6 doses total).', 'Headache, dizziness, nausea, vomiting, loss of appetite.', false, false, true, 'Yes'),
  ('Omeprazole', 'Omeprazole', 'Proton Pump Inhibitor', 'Treats acid reflux, stomach ulcers, and heartburn.', 'Adults: 20-40mg once daily before meals.', 'Headache, nausea, diarrhea, stomach pain.', false, false, false, 'No'),
  ('Amlodipine', 'Amlodipine Besylate', 'Calcium Channel Blocker', 'Treats high blood pressure and chest pain (angina).', 'Adults: 5-10mg once daily.', 'Swelling of ankles, flushing, headache, dizziness.', false, false, false, 'Yes');

-- pharmacies: 21 rows
insert into public.pharmacies (name, location, address, phone, email, latitude, longitude, opening_hours, open_24hrs, open) values
  ('Goodlife Pharmacy Westgate', 'Westlands, Nairobi', 'Westgate Mall, Westlands', '+254710000001', 'westgate@goodlife.co.ke', -1.2637, 36.803, 'Mon-Sun 8am-9pm', false, true),
  ('Medplus Pharmacy CBD', 'Nairobi CBD', 'Moi Avenue, Nairobi', '+254710000002', 'cbd@medplus.co.ke', -1.2841, 36.8155, 'Mon-Sat 8am-8pm', false, true),
  ('City Chemist Nairobi', 'Nairobi CBD', 'Kenyatta Avenue, Nairobi', '+254710000003', null, -1.2864, 36.8172, 'Open 24 Hours', true, true),
  ('HealthPlus Karen', 'Karen, Nairobi', 'Karen Shopping Centre', '+254710000004', 'karen@healthplus.co.ke', -1.3182, 36.7104, 'Mon-Sun 8am-8pm', false, true),
  ('Flamingo Pharmacy Eastleigh', 'Eastleigh, Nairobi', '1st Avenue, Eastleigh', '+254710000005', null, -1.2736, 36.8508, 'Mon-Sun 7am-10pm', false, true),
  ('Coast Pharmacy Mombasa', 'Mombasa CBD', 'Digo Road, Mombasa', '+254720000001', 'coast@pharmacy.co.ke', -4.0435, 39.6682, 'Mon-Sat 8am-8pm', false, true),
  ('Goodlife Nyali', 'Nyali, Mombasa', 'Nyali Centre, Mombasa', '+254720000002', 'nyali@goodlife.co.ke', -4.0167, 39.7167, 'Mon-Sun 8am-9pm', false, true),
  ('Port Chemist Mombasa', 'Mombasa CBD', 'Makadara Road, Mombasa', '+254720000003', null, -4.0523, 39.6601, 'Open 24 Hours', true, true),
  ('Lakeside Pharmacy', 'Kisumu CBD', 'Oginga Odinga Street, Kisumu', '+254730000001', 'lakeside@pharmacy.co.ke', -0.0917, 34.768, 'Mon-Sat 8am-7pm', false, true),
  ('City Chemist Kisumu', 'Kisumu CBD', 'Jomo Kenyatta Highway, Kisumu', '+254730000002', null, -0.1022, 34.7617, 'Open 24 Hours', true, true),
  ('Goodlife Pharmacy Nakuru', 'Nakuru CBD', 'Kenyatta Avenue, Nakuru', '+254710123456', 'nakuru@goodlife.co.ke', -0.28, 36.066, 'Mon-Sun 8am-9pm', false, true),
  ('City Chemist Nakuru', 'Nakuru CBD', 'Mosque Road, Nakuru', '+254743456789', 'citychemist@nakuru.co.ke', -0.281, 36.068, 'Open 24 Hours', true, true),
  ('Rift Pharmacy Eldoret', 'Eldoret CBD', 'Uganda Road, Eldoret', '+254740000001', 'rift@pharmacy.co.ke', 0.5143, 35.2698, 'Mon-Sat 8am-8pm', false, true),
  ('Medplus Eldoret', 'Eldoret CBD', 'Kenyatta Street, Eldoret', '+254740000002', 'eldoret@medplus.co.ke', 0.52, 35.275, 'Open 24 Hours', true, true),
  ('Thika Pharmacy', 'Thika CBD', 'Commercial Street, Thika', '+254750000001', null, -1.0332, 37.0693, 'Mon-Sat 8am-7pm', false, true),
  ('Mount Kenya Pharmacy', 'Nyeri CBD', 'Kimathi Way, Nyeri', '+254760000001', null, -0.4167, 36.95, 'Mon-Sat 8am-7pm', false, true),
  ('Machakos Chemist', 'Machakos CBD', 'Wote Road, Machakos', '+254770000001', null, -1.5177, 37.2634, 'Mon-Sat 8am-7pm', false, true),
  ('Kisii Pharmacy', 'Kisii CBD', 'Hospital Road, Kisii', '+254780000001', null, -0.6817, 34.7667, 'Mon-Sat 8am-7pm', false, true),
  ('Malindi Pharmacy', 'Malindi, Kilifi County', 'Lamu Road, Malindi', '+254790000001', null, -3.2138, 40.1169, 'Mon-Sat 8am-6pm', false, true),
  ('Garissa Chemist', 'Garissa CBD', 'Hospital Road, Garissa', '+254700000001', null, -0.4532, 42.0034, 'Mon-Sat 8am-6pm', false, true),
  ('Western Pharmacy Kakamega', 'Kakamega CBD', 'Kakamega-Kisumu Road', '+254700000002', null, 0.2827, 34.7519, 'Mon-Sat 8am-7pm', false, true);
